# ============================================================
# Run one agent-ready Regression Kriging iteration from JSON request.
# ============================================================

source("scripts/agent_utils.R")

agent_parse_args <- function(args) {
  out <- list()
  i <- 1L
  while (i <= length(args)) {
    key <- args[[i]]
    if (startsWith(key, "--")) {
      nm <- sub("^--", "", key)
      val <- TRUE
      if (i + 1L <= length(args) && !startsWith(args[[i + 1L]], "--")) {
        val <- args[[i + 1L]]
        i <- i + 1L
      }
      out[[nm]] <- val
    }
    i <- i + 1L
  }
  out
}

make_failed_result <- function(run_id, target_field, output_folder, status, message, log_file = NA_character_) {
  list(
    run_id = run_id,
    requested_run_id = requested_run_id,
    target_field = target_field,
    status = status,
    output_folder = agent_norm_path(output_folder),
    quality = list(final_grade = NULL, final_score = NULL, decision_hint = "MANUAL_REVIEW_REQUIRED"),
    metrics = list(rk_rmse = NULL, rk_mae = NULL, rk_me = NULL, rk_r2_pred = NULL, nrmse_mean = NULL, rpd = NULL),
    model_comparison = list(regression_rmse = NULL, ordinary_kriging_rmse = NULL, regression_kriging_rmse = NULL),
    variogram = list(model = NULL, nugget = NULL, psill = NULL, sill = NULL, range = NULL, practical_range = NULL, nugget_sill_ratio = NULL, range_hit_max = NULL),
    warnings = c(message),
    recommendations = c("Fix the request or inspect the run log before rerunning."),
    files = list(run_log = agent_norm_path(log_file)),
    missing_outputs = c("RK engine did not complete successfully.")
  )
}

args <- agent_parse_args(commandArgs(trailingOnly = TRUE))
request_path <- args$request %||% args$r %||% "agent/requests/run_request_template.json"
target_override <- args$target %||% args$Target %||% NULL

agent_ensure_dir("agent/responses")
agent_ensure_dir("agent/history")
agent_ensure_dir("agent/decisions")

cat("[INFO] Starting agent-ready RK run...\n")
cat("[INFO] Request: ", request_path, "\n", sep = "")

request <- agent_read_json(request_path)
request$target_field <- target_override %||% request$target_field %||% "auto"
run_id <- agent_safe_name(request$run_id %||% paste0(request$target_field, "_iter_", format(Sys.time(), "%Y%m%d_%H%M%S")))
requested_run_id <- run_id
target_field <- request$target_field %||% "auto"
target_name <- agent_safe_name(target_field)
output_root <- request$output_root %||% "output/agent_runs"
agent_ensure_dir(output_root)
output_folder <- file.path(output_root, run_id)
if (dir.exists(output_folder) && length(list.files(output_folder, all.files = FALSE, no.. = TRUE)) > 0) {
  run_id <- agent_safe_name(paste0(run_id, "_", format(Sys.time(), "%Y%m%d_%H%M%S")))
  output_folder <- file.path(output_root, run_id)
  cat("[INFO] Requested run_id already exists; using new run_id: ", run_id, "\n", sep = "")
}
history_dir <- file.path("agent/history", run_id)
agent_ensure_dir(history_dir)
cat("[INFO] Target: ", target_field, "\n", sep = "")
cat("[INFO] Run ID: ", run_id, "\n", sep = "")

safety_limits <- agent_merge_lists(agent_default_safety_limits(), request$safety_limits %||% list())
if (!isTRUE(safety_limits$allow_modify_raw_data %||% FALSE)) {
  protected_in_request <- intersect(names(request$parameters %||% list()), agent_protected_parameters())
  if (length(protected_in_request) > 0) stop(paste0("Request tries to modify protected setting(s): ", paste(protected_in_request, collapse = ", ")))
}
param_validation <- agent_validate_parameter_list(request$parameters %||% list(), safety_limits)
if (length(param_validation$rejected) > 0) {
  msg <- paste(paste(names(param_validation$rejected), unlist(param_validation$rejected), sep = ": "), collapse = "; ")
  result <- make_failed_result(run_id, target_field, output_folder, "invalid_request", msg)
  out_file <- file.path("agent/responses", paste0(run_id, "_run_result.json"))
  agent_write_json(result, out_file)
  stop(paste0("Invalid run request: ", msg))
}

override_file <- file.path(history_dir, paste0("override_", run_id, ".R"))
override_lines <- c(
  "# Auto-generated by scripts/agent_run.R. Do not edit source config for agent iterations.",
  paste0("RUN_NAME_OVERRIDE <- ", agent_r_literal(run_id)),
  paste0("TARGET_FIELD <- ", agent_r_literal(target_field)),
  paste0("OUTPUT_ROOT <- ", agent_r_literal(output_root)),
  "ASK_OUTPUT_FOLDER <- FALSE",
  "RUN_CROSS_VALIDATION <- TRUE"
)
for (nm in names(param_validation$accepted)) {
  override_lines <- c(override_lines, paste0(nm, " <- ", agent_r_literal(param_validation$accepted[[nm]])))
}
writeLines(override_lines, override_file, useBytes = TRUE)
agent_write_json(request, file.path(history_dir, "request.json"))

log_file <- file.path(history_dir, paste0("agent_run_", run_id, ".log"))
rscript <- Sys.which("Rscript")
if (!nzchar(rscript)) stop("Rscript was not found on PATH.")
cat("[INFO] Running Rscript scripts/main.R...\n")
old_override <- Sys.getenv("RK_CONFIG_OVERRIDE", unset = NA_character_)
Sys.setenv(RK_CONFIG_OVERRIDE = normalizePath(override_file, winslash = "/", mustWork = FALSE))
status <- system2(rscript, c("scripts/main.R"), stdout = log_file, stderr = log_file)
if (is.na(old_override)) Sys.unsetenv("RK_CONFIG_OVERRIDE") else Sys.setenv(RK_CONFIG_OVERRIDE = old_override)

report_dir <- file.path(output_folder, "06_report")
eval_json <- file.path(report_dir, "json", paste0("evaluation_", target_name, ".json"))
model_csv <- file.path(report_dir, "tables", paste0("model_comparison_", target_name, ".csv"))
summary_csv <- file.path(report_dir, paste0("summary_", target_name, ".csv"))
html_report <- file.path(report_dir, paste0("index_", target_name, ".html"))
interactive_variogram <- file.path(report_dir, "interactive", paste0("variogram_interactive_", target_name, ".html"))
variogram_diag <- file.path(report_dir, "json", paste0("variogram_diagnostics_", target_name, ".json"))
cv_results <- file.path(report_dir, "tables", paste0("cv_results_", target_name, ".csv"))
neighbor_tuning_csv <- file.path(report_dir, "tables", paste0("neighbor_tuning_", target_name, ".csv"))
rk_report_csv <- file.path(report_dir, "tables", paste0("rk_report_", target_name, ".csv"))
engine_log <- file.path(report_dir, "logs", paste0("run_log_", target_name, ".txt"))

missing <- character(0)
for (p in c(eval_json, model_csv, cv_results, html_report, interactive_variogram, engine_log)) {
  if (!file.exists(p)) missing <- c(missing, paste0(agent_norm_path(p), " not available"))
}

if (!identical(status, 0L) || !file.exists(eval_json)) {
  msg <- paste0("RK engine failed or evaluation JSON was not produced. Exit code: ", status)
  result <- make_failed_result(run_id, target_field, output_folder, "failed", msg, log_file)
  result$missing_outputs <- unique(c(result$missing_outputs, missing))
} else {
  evaluation <- agent_read_json(eval_json)
  model_comparison <- agent_read_csv_if_exists(model_csv)
  rk_report <- agent_read_csv_if_exists(rk_report_csv)
  vg <- evaluation$variogram %||% list()
  cv <- evaluation$cross_validation$metrics %||% list()
  cv_info <- evaluation$cross_validation %||% list()
  cls <- evaluation$class_evaluation %||% list()
  unc <- evaluation$uncertainty %||% list()
  q <- evaluation$quality %||% list()
  range_max <- request$parameters$VARIOGRAM_RANGE_MAX %||% NA_real_
  range_hit_max <- FALSE
  if (is.finite(as.numeric(range_max)) && is.finite(as.numeric(vg$range %||% NA_real_))) {
    range_hit_max <- abs(as.numeric(vg$range) - as.numeric(range_max)) / max(1, as.numeric(range_max)) < 0.02
  }
  result <- list(
    run_id = run_id,
    requested_run_id = requested_run_id,
    target_field = target_field,
    status = "completed",
    output_folder = agent_norm_path(output_folder),
    quality = list(final_grade = q$final_grade %||% NULL, final_score = q$final_score %||% NULL, decision_hint = NULL),
    metrics = list(
      rk_rmse = cv$RMSE %||% NULL,
      rk_mae = cv$MAE %||% NULL,
      rk_me = cv$ME %||% NULL,
      rk_r2_pred = cv$R2_pred %||% NULL,
      nrmse_mean = cv$NRMSE_mean %||% NULL,
      rpd = cv$RPD %||% NULL
    ),
    model_comparison = list(
      regression_rmse = agent_pick_model_metric(model_comparison, "Regression-only", "RMSE"),
      ordinary_kriging_rmse = agent_pick_model_metric(model_comparison, "Ordinary Kriging", "RMSE"),
      regression_kriging_rmse = agent_pick_model_metric(model_comparison, "Regression Kriging", "RMSE")
    ),
    cross_validation = list(
      method = cv_info$method %||% NULL,
      cv_folds = cv_info$cv_folds %||% NULL,
      refit_variogram = cv_info$refit_variogram %||% NULL,
      leakage_guard = cv_info$leakage_guard %||% NULL
    ),
    class_evaluation = list(
      enabled = cls$enabled %||% FALSE,
      class_accuracy = cls$class_accuracy %||% NULL,
      within_one_class_rate = cls$within_one_class_rate %||% NULL,
      severe_misclassification_rate = cls$severe_misclassification_rate %||% NULL
    ),
    uncertainty = list(
      available = unc$available %||% FALSE,
      mean_sd = unc$mean_sd %||% NULL,
      max_sd = unc$max_sd %||% NULL,
      high_uncertainty_area_percent = unc$high_uncertainty_area_percent %||% NULL,
      note = "Residual kriging STD only; regression and covariate uncertainty are not included."
    ),
    kriging = list(
      auto_neighbors_enabled = if (nrow(rk_report) > 0 && "auto_neighbors_enabled" %in% names(rk_report)) rk_report$auto_neighbors_enabled[1] else NULL,
      auto_neighbors_method = if (nrow(rk_report) > 0 && "auto_neighbors_method" %in% names(rk_report)) rk_report$auto_neighbors_method[1] else NULL,
      selected_nmax_neighbors = if (nrow(rk_report) > 0 && "nmax_neighbors" %in% names(rk_report)) rk_report$nmax_neighbors[1] else NULL,
      selected_search_radius = if (nrow(rk_report) > 0 && "search_radius" %in% names(rk_report)) rk_report$search_radius[1] else NULL
    ),
    variogram = list(
      model = vg$model %||% NULL,
      nugget = vg$nugget %||% NULL,
      psill = vg$partial_sill %||% vg$psill %||% NULL,
      sill = vg$sill %||% NULL,
      range = vg$range %||% NULL,
      practical_range = vg$practical_range %||% NULL,
      nugget_sill_ratio = vg$nugget_sill_ratio %||% NULL,
      range_hit_max = range_hit_max
    ),
    warnings = evaluation$warnings %||% character(0),
    recommendations = evaluation$recommendations %||% character(0),
    files = list(
      html_report = agent_norm_path(html_report),
      evaluation_json = agent_norm_path(eval_json),
      model_comparison_csv = agent_norm_path(model_csv),
      cv_results_csv = agent_norm_path(cv_results),
      neighbor_tuning_csv = agent_norm_path(neighbor_tuning_csv),
      rk_report_csv = agent_norm_path(rk_report_csv),
      variogram_diagnostics_json = agent_norm_path(variogram_diag),
      interactive_variogram = agent_norm_path(interactive_variogram),
      run_log = agent_norm_path(engine_log),
      agent_log = agent_norm_path(log_file)
    ),
    missing_outputs = if (length(missing) == 0) list() else unique(missing)
  )
  result$quality$decision_hint <- agent_decision_hint(result)
}

response_file <- file.path("agent/responses", paste0(run_id, "_run_result.json"))
history_result_file <- file.path(history_dir, "run_result.json")
run_folder_result_file <- file.path(output_folder, "run_result.json")
agent_write_json(result, response_file)
agent_write_json(result, history_result_file)
agent_write_json(result, run_folder_result_file)
cat("[INFO] RK completed.\n")
cat("[INFO] Evaluation report: ", agent_norm_path(html_report), "\n", sep = "")
cat("[INFO] Run result JSON: ", agent_norm_path(response_file), "\n", sep = "")
if (!identical(result$status, "completed")) quit(status = 1L)